services:
    ngrok:
        image: ngrok/ngrok:latest
        network_mode: "host"
        restart: unless-stopped
        command:
          - "start"
          - "--all"
          - "--config"
          - "/ngrokconfig.yaml"
        volumes:
          - ./ngrokconfig.yaml:/ngrokconfig.yaml
        ports:
          - 4040:4040
    webgoat:
        image: webgoat/webgoat-8.0
        restart: unless-stopped
        basic_auth:
          - "bob:bob"
        ports:
          - 8080:8080
    juiceshop:
        image: bkimminich/juice-shop
        restart: unless-stopped
        ports:
          - 3050:3000
        basic_auth:
          - "bob:bob"