authtoken: <<AUTHTOKEN>>
version: 2
console_ui: true
tunnels:
  webgoat:
    proto: http
    addr: 8080
    basic_auth:
      - "bob:password"
  juiceshop:
    proto: http
    addr: 3050
    basic_auth:
      - "bob:password"
